### ISSUE TITLE
Adding support for room temperature sensor?

### ISSUE THREAD

**Issue by fredlcore** [DE-cr/BSBmonCR#1]
I think BSBmonCR already provides a lot of useful functions, but how about adding support for DHT22 and/or DS18B20 sensors and use their temperature values to be sent automatically to the heater via BSB-LAN?
I'm still looking for a solution that could work on [this device](https://www.az-delivery.de/products/az-touch-wandgehauseset-mit-touchscreen-fur-esp8266-und-esp32) and be a complete replacement for a room unit. I think BSBmonCR would be a very good candidate for that...

**Comment by DE-cr** [comment]
Of course that could be done. Easily, probably.

As I'm not aware of *any* other BSBmonCR devices besides my own, and as that kind of functionally is nothing *I* am missing, I'd rather leave that implementation for others to do on their BSBmonCR forks - should they exist.

(The only function I have ever wished for in BSBmonCR and not implemented (yet?) is a button for a DHW push, which I do a couple of times each year(!).)

**Comment by fredlcore** [comment]
The reason I suggest this is that I will select a few external projects for the manual that can complement BSB-LAN in a useful way. Regarding the simulation of a room unit, there are several projects that realize isolated functions of a room unit, but there is none that exactly mirrors those functions (even though they might be adding other useful features). I saw yours as the one coming closest to that, but I also won't be spending time to implement features in someone else's code, so I'll just leave it as it is.

**Comment by DE-cr** [comment]
For me, BSBmonCR already does complement BSB-LAN (and our already existing off-the-shelf room unit) in a (very) useful way. :)

Maybe just point others to BSBmonCR for some ideas of what could be done, so that they can build on parts of its design / code (while mentioning the source, should they decide to share their work with others)?

**Comment by fredlcore** [comment]
That's what we have done for years, but in the future, I want to streamline things. My concern is the demand from users who keep asking me about room unit replacements, and apparently the three(?) different approaches (including the room unit simulation built into BSB-LAN) we showcased before do not meet these demands. That doesn't say anything about the individual use of the projects, of course, but it is something I will have to address.
